# Generated by Django 5.0.3 on 2024-04-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalation', '0002_log_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escalation',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='log_permission',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='log_permission',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usergroupdefault',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='usergroupdefault',
            old_name='user_id',
            new_name='user',
        ),
    ]
