# Generated by Django 5.0.3 on 2024-05-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalation', '0005_escalation_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logpermission',
            name='is_active',
        ),
        migrations.AddField(
            model_name='logpermission',
            name='status',
            field=models.CharField(blank=True, choices=[('activate', 'Activate'), ('desactivate', 'Desactivate'), ('denied', 'Denied'), ('pending', 'Pending')], default='desactivates', max_length=11),
        ),
        migrations.AlterField(
            model_name='escalation',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
