# Generated by Django 5.0.3 on 2024-05-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalation', '0006_remove_logpermission_is_active_logpermission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpermission',
            name='status',
            field=models.CharField(blank=True, choices=[('activate', 'Activate'), ('desactivate', 'Desactivate'), ('denied', 'Denied'), ('pending', 'Pending')], default='desactivate', max_length=11),
        ),
    ]
