# Generated by Django 5.0.3 on 2024-05-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalation', '0007_alter_logpermission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpermission',
            name='status',
            field=models.CharField(choices=[('activate', 'Activate'), ('desactivate', 'Desactivate'), ('denied', 'Denied'), ('pending', 'Pending')], default='desactivate', max_length=11),
        ),
    ]
