# Generated by Django 5.0.3 on 2024-06-27 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalation', '0008_alter_logpermission_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalation',
            name='is_used',
        ),
        migrations.CreateModel(
            name='UserEscalationIsUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('escalation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userescalationisused', to='escalation.escalation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userescalationisused', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
